// Generated by CoffeeScript 1.3.3
(function() {
  var Quotes3D, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  /*
  3D Carousel for blockquotes
  */


  root.Quotes3D = Quotes3D = (function() {
    var INTERVAL_MS;

    function Quotes3D(DOMel) {
      this.DOMel = DOMel;
      this.next = __bind(this.next, this);

      this.handleClick = __bind(this.handleClick, this);

      this.$quotes = $(this.DOMel).find('blockquote');
      this.createPagination();
      this.showQuote(0);
      this.start();
    }

    INTERVAL_MS = 5000;

    Quotes3D.prototype.createPagination = function() {
      var $quote, list, _i, _len, _ref;
      list = $('<ul>', {
        "class": 'pagination'
      });
      _ref = this.$quotes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        $quote = _ref[_i];
        list.append($('<li>'));
      }
      $(this.DOMel).append(list);
      this.$pagination = list.find('li');
      return this.$pagination.click(this.handleClick);
    };

    Quotes3D.prototype.handleClick = function(e) {
      this.showQuote($(e.target).index());
      return this.stop();
    };

    Quotes3D.prototype.next = function() {
      return this.showQuote((this.index + 1) % this.$quotes.length);
    };

    Quotes3D.prototype.previous = function() {
      return this.showQuote(Math.abs((this.index - 1) % this.$quotes.length));
    };

    Quotes3D.prototype.showQuote = function(newIndex) {
      if (newIndex === this.index) {
        return;
      }
      this.$quotes.removeClass('rolling');
      this.$quotes.eq(this.index).addClass('rolling');
      this.$quotes.eq(newIndex).addClass('rolling');
      this.index = newIndex;
      this.$quotes.removeClass('before');
      this.$quotes.removeClass('after');
      this.$quotes.filter(":lt(" + newIndex + ")").addClass('before');
      this.$quotes.filter(":gt(" + newIndex + ")").addClass('after');
      this.$pagination.removeClass('selected');
      return this.$pagination.eq(newIndex).addClass('selected');
    };

    Quotes3D.prototype.start = function() {
      return this.interval = setInterval(this.next, INTERVAL_MS);
    };

    Quotes3D.prototype.stop = function() {
      return clearInterval(this.interval);
    };

    return Quotes3D;

  })();

}).call(this);
